[build]
  command = "CI=false npm run build"
  publish = ".next"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://your-backend-url.run.app"
  CI = "false"
